apply plugin: 'com.android.application'

android {
    namespace 'com.smsbot'
    compileSdk 33

    defaultConfig {
        applicationId "com.smsbot"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.10.0'
}
